collated: true
variants:
- name: default
  context:
    name: default
- name: book
  context:
    name: book
- name: checkmark
  context:
    name: checkmark
- name: loupe
  context:
    name: loupe
- name: design
  context:
    name: design
- name: development
  context:
    name: development
- name: laws
  context:
    name: laws
- name: search
  context:
    name: search
- name: ex-circle
  context:
    name: ex-circle
- name: check-circle
  context:
    name: check-circle
- name: cancel-rect
  context:
    name: cancel-rect
- name: chevron-up
  context:
    name: chevron-up
- name: chevron-down
  context:
    name: chevron-down
- name: chevron-left
  context:
    name: chevron-left
- name: chevron-right
  context:
    name: chevron-right
- name: arrow-up
  context:
    name: arrow-up
- name: arrow-down
  context:
    name: arrow-down
- name: arrow-left
  context:
    name: arrow-left
- name: arrow-right
  context:
    name: arrow-right
- name: comments
  context:
    name: comments
- name: audio-description
  context:
    name: audio-description
- name: external-link
  context:
    name: external-link
- name: warning
  context:
    name: warning