collated: true
variants:
- name: default
  context:
    label: Button
- name: disabled
  context:
    label: Disabled button
    disabled: true
- name: link
  context:
    label: Link Button
    href: '#'
    mods: [more]
- name: icon
  context:
    type: icon
    icon: search
    label: Icon Button
    href: '#'
    mods: ["icon"]
