collated: true
variants:
- name: default
  context:
    label: Button
- name: disabled
  context:
    label: Disabled button
    disabled: true
- name: secondary
  context:
    label: Secondary button
    mods: ['secondary']
- name: link
  context:
    label: Link Button
    href: '#'
    mods: ['more']
- name: link-secondary
  context:
    label: Secondary Link Button
    href: '#'
    mods: ['more', 'secondary']
- name: icon
  context:
    type: icon
    icon: search
    label: Icon Button
    href: '#'
    mods: ["icon"]
- name: fake
  context:
    type: fake
    label: Fake button
    mods: ['fake']